# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    wishlist.controller.front:
        class: WellCommerce\Bundle\WishlistBundle\Controller\Front\WishlistController
        arguments: ['@wishlist.manager']
        calls:
            - [setContainer, ['@service_container']]

    wishlist.layout_box.controller:
        class: WellCommerce\Bundle\WishlistBundle\Controller\Box\WishlistBoxController
        arguments: ['@wishlist.manager']
        calls:
            - [setContainer, ['@service_container']]

    wishlist.configurator:
        class: WellCommerce\Bundle\WishlistBundle\Configurator\WishlistBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    wishlist.twig.extension:
        class: WellCommerce\Bundle\WishlistBundle\Twig\WishlistExtension
        tags:
            - { name: twig.extension }
        arguments:
            - '@wishlist.repository'
